name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test and generate coverage report (lcov format)
      run: |
        cd ./tests/coverlet-library-unittests/
        dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov --no-restore
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@v1.0.1
      with:
        path-to-lcov: ./tests/coverlet-library-unittests/TestResults/coverage.info
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1
    - name: Run sonarqube
      env:
        # to get access to secrets.SONAR_TOKEN, provide GITHUB_TOKEN
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sonar-scanner
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
           -Dsonar.organization=antao
           -Dsonar.host.url=https://sonarcloud.io/
           -Dsonar.projectKey=learning-measuring-code-coverage
